[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.docker-clear]
script = { file = "./scripts/docker-clear.sh" }

[tasks.docker]
dependencies = [
    "docker-clear"
]
command = "docker"
args = [
    "compose",
    "-f", "./deploy/docker-compose.dev.yml",
    "up",
    "--build"
]

[tasks.docker-start]
command = "docker"
args = [
    "compose",
    "-f", "./deploy/docker-compose.dev.yml",
    "start"
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fix]
command = "cargo"
args = ["fix", "--allow-dirty"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.test-watch]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "nextest run"]

[tasks.local-coverage]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = [
    "tarpaulin",
    "--verbose",
    "--all-features",
    "--workspace",
    "--timeout",
    "240",
    "--out",
    "Xml"
]

[tasks.ci]
dependencies = [
    "build",
    "test"
]

[tasks.ci-coverage]
command = "cargo"
args = [
    "tarpaulin",
    "--verbose",
    "--all-features",
    "--workspace",
    "--timeout",
    "240",
    "--out",
    "Xml"
]
