version: '3'

services:
  app:
    container_name: calendar
    command: bash -c "cargo watch -x run | bunyan"
    build:
      context: ..
      dockerfile: deploy/dockerfiles/dev.Dockerfile
      args:
        APP_ENV: local
    env_file:
      - ../.env
    volumes:
      - ..:/app
    ports:
      - "8080:8080"
