[package]
name = "calendar-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder = "0.12.0"
getset = "0.1.2"

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_with = "3.3.0"
